import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import { BsSearch } from "react-icons/bs";
import Forecast from "../components/Forecast";
import Spinner from "../components/Spinner";

export default function Home() {
  const [city, setCity] = useState("");
  const [forecast, setForecast] = useState({});
  const [loading, setLoading] = useState(false);
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_FORECAST_KEY}`;
  const fetchForecast = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setForecast(response.data);
      // console.log(response.data);
    });
    setCity("");
    setLoading(false);
  };

  if (loading) {
    return <Spinner />;
  } else {
    return (
      <div>
        <Head>
          <title>Forecast - NextJS Weather App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* Generates Overlay */}
        <div className="absolute top-0 left-0 right-0 bottom-0 bg-[#2222]/60 z-[1]" />

        {/* Application Background */}
        <Image
          src="https://images.unsplash.com/photo-1576122800181-bc3194265f27?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
          layout="fill"
          className="object-cover"
          alt="Hawaii weather"
        />

        {/* Search Form */}
        <div className="relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-[whitesmoke]  z-10">
          <form
            onSubmit={fetchForecast}
            className="flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-[whitesmoke] rounded-2xl"
          >
            <div>
              <input
                onChange={(e) => setCity(e.target.value)}
                className="bg-transparent border-none text-[whitesmoke] font-normal focus:outline-none text-xl placeholder:text-[whitesmoke]"
                type="text"
                placeholder="Search By Location"
              />
            </div>
            <button onClick={fetchForecast}>
              <BsSearch size={18} />
            </button>
          </form>
        </div>

        {/* Forecast Details */}

        {forecast.main && <Forecast data={forecast} />}
      </div>
    );
  }
}
